# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Hosted VS2017

steps:

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'AzureStack-Bellevue'
    ScriptType: 'InlineScript'
    Inline: |
      New-Item -Path "$(Build.SourcesDirectory)" -Name "az-new" -ItemType "directory"
      $acc = Get-AzStorageAccount
      Get-AzStorageBlobContent -Container "azaccountscontainer" -Blob "Az.Accounts.2.1.2.nupkg" -Destination "$(Build.SourcesDirectory)\az-new" -Context $acc.Context
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
    workingDirectory: '$(Build.SourcesDirectory)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'ls'
    pwsh: true
