FROM mcr.microsoft.com/powershell:centos-7

ARG REPOSITORY=PSGallery
ARG MODULE=Az
ARG CONFIG=config
ARG AZURERM_CONTEXT_SETTINGS=AzureRmContextSettings.json
ARG AZURE=/root/.Azure
ARG VCS_REF="none"
ARG BUILD_DATE=
ARG VERSION=1.10.0
ARG IMAGE_NAME=mcr.microsoft.com/azure-stack-powershell:${VERSION}-centos-7
ARG AZURESTACK_PROFILE=2020-09-01-hybrid
ARG AZURESTACK_VERSION=2.1.0
ARG READINESS_CHECKER_VERSION=1.2005.1269-preview

ENV AZUREPS_HOST_ENVIRONMENT="dockerImage/${VERSION}-centos-7"

LABEL maintainer="AzureStack PowerShell Team <azsdevexp@microsoft.com>" \
      readme.md="http://aka.ms/azspsdockerreadme" \
      description="This Dockerfile will install the latest supported version of Azure PowerShell that works with AzureStack Hub." \
      org.label-schema.build-date=${BUILD_DATE} \
      org.label-schema.usage="http://aka.ms/azspsdocker" \
      org.label-schema.url="http://aka.ms/azspsdockerreadme" \
      org.label-schema.vcs-url="https://github.com/Azure/azure-powershell" \
      org.label-schema.name="azure powershell" \
      org.label-schema.vendor="AzureStack PowerShell" \
      org.label-schema.version=${VERSION} \
      org.label-schema.schema-version="1.0" \
      org.label-schema.vcs-ref=${VCS_REF} \
      org.label-schema.docker.cmd="docker run --rm ${IMAGE_NAME} pwsh -c '\$PSVERSIONTABLE'" \
      org.label-schema.docker.cmd.devel="docker run -it --rm -e 'DebugPreference=Continue' ${IMAGE_NAME} pwsh" \
      org.label-schema.docker.cmd.test="currently not available" \
      org.label-schema.docker.cmd.help="docker run --rm ${IMAGE_NAME} pwsh -c Get-Help"

# install azure-powershell and azure stack admin modules from PSGallery

COPY scripts/* /

SHELL ["pwsh", "-Command"]

RUN ./Install-AzureStackPowerShell.ps1 -REPOSITORY $Env:REPOSITORY -AZURESTACK_PROFILE $Env:AZURESTACK_PROFILE -AZURESTACK_VERSION $Env:AZURESTACK_VERSION
RUN ./Install-AzureStackTools.ps1
RUN Install-Module -Name Microsoft.AzureStack.ReadinessChecker -RequiredVersion $Env:READINESS_CHECKER_VERSION -AllowPrerelease -Force

# create AzureRmContextSettings.json before it was generated
COPY ${CONFIG}/${AZURERM_CONTEXT_SETTINGS} ${AZURE}/${AZURERM_CONTEXT_SETTINGS}

CMD [ "pwsh" ]